name: SkyBlockCore
version: '${project.version}'
main: com.possiest.skyblockcore.SkyBlockCore
api-version: 1.19
authors: [ MathiasClari ]
description: Made with love by Possiest
commands:
  ssb:
  is:
  isdel:
  spawn:
    aliases:
      - s